### ISSUE TITLE
Make Course Links Appear on hover only

### ISSUE THREAD

**Issue by dcartertod** [robert-carroll/ccsd-canvas#1]
Not a github user, so this is the only way I know to suggest this, but you can make the links appear only when hovering using a hidden visibility by default and a hover selector:

```
div.rc-course-links ul { 
	visibility: hidden;
...

[data-automation="courses list"] tr:hover .rc-course-links ul {
	visibility: visible !important;
}
```

**Comment by robert-carroll** [comment]
I've opened it up for discussion [here](https://community.canvaslms.com/thread/23634-custom-javascript-for-admincourses-page#comment-117233). This probably comes down to user/school preference. Can easily provide both, and keep default visible with comments.

**Comment by robert-carroll** [comment]
So far the only comment is that hiding content until hover is bad for accessibility.
